inputs = [
    {  # 0 Increase throttle only
        "left": False,
        "right": False,
        "center": False,
        "increase_throttle": True,
        "increase_brake": False,
        "reset_throttle": False,
        "reset_brake": False,
    },
    {  # 1 Increase throttle and steer increasingly left
        "left": True,
        "right": False,
        "center": False,
        "increase_throttle": True,
        "increase_brake": False,
        "reset_throttle": False,
        "reset_brake": False,
    },
    {  # 2 Increase throttle and steer increasingly right
        "left": False,
        "right": True,
        "center": False,
        "increase_throttle": True,
        "increase_brake": False,
        "reset_throttle": False,
        "reset_brake": False,
    },
    {  # 3 Hold everything the same
        "left": False,
        "right": False,
        "center": False,
        "increase_throttle": False,
        "increase_brake": False,
        "reset_throttle": False,
        "reset_brake": False,
    },
    {  # 4 Steer increasingly left only
        "left": True,
        "right": False,
        "center": False,
        "increase_throttle": False,
        "increase_brake": False,
        "reset_throttle": False,
        "reset_brake": False,
    },
    {  # 5 Steer increasingly right only
        "left": False,
        "right": True,
        "center": False,
        "increase_throttle": False,
        "increase_brake": False,
        "reset_throttle": False,
        "reset_brake": False,
    },
    {  # 5 Center steering only
        "left": False,
        "right": False,
        "center": True,
        "increase_throttle": False,
        "increase_brake": False,
        "reset_throttle": False,
        "reset_brake": False,
    },
    {  # 6 Brake harder only
        "left": False,
        "right": False,
        "center": False,
        "increase_throttle": False,
        "increase_brake": True,
        "reset_throttle": False,
        "reset_brake": False,
    },
    {  # 7 Brake harder and steer increasingly left
        "left": True,
        "right": False,
        "center": False,
        "increase_throttle": False,
        "increase_brake": True,
        "reset_throttle": False,
        "reset_brake": False,
    },
    {  # 8 Brake harder and steer increasingly right
        "left": False,
        "right": True,
        "center": False,
        "increase_throttle": False,
        "increase_brake": True,
        "reset_throttle": False,
        "reset_brake": False,
    },
    {  # 9 Fully lift off throttle only
        "left": False,
        "right": False,
        "center": False,
        "increase_throttle": False,
        "increase_brake": False,
        "reset_throttle": True,
        "reset_brake": False,
    },
    {  # 10 Fully lift off brake only
        "left": False,
        "right": False,
        "center": False,
        "increase_throttle": False,
        "increase_brake": False,
        "reset_throttle": False,
        "reset_brake": True,
    },
    # {  # 11 Toggle parking brake only (does nothing for now)
    #     "left": False,
    #     "right": False,
    #     "center": False,
    #     "increase_throttle": False,
    #     "increase_brake": False,
    #     "reset_throttle": False,
    #     "reset_brake": False,
    # },
]

action_forward_idx = 0  # Increase throttle, don't turn
